del /f /s *.aps
del /f /s /A:H *.suo
del /f /s *.sdf
del /f /s *.pdb
del /f /s *.ilk
del /f /s *.exe
del /f /s *.ipch
del /f /s *.tlog
del /f /s *.lastbuildstate
del /f /s *.log
del /f /s *.obj
del /f /s *.pch
del /f /s *.res
del /f /s *.manifest
del /f /s *.idb
del /f /s *.exp
del /f /s *.lib
del /f /s *.dll
del /f /s *.mac
del /f /s *.bmf
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.sys
del /f /s *.obj.oacr.root.amd64fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml
del /f /s *.obj.oacr.root.x86fre.pft.xml